spring:
  profiles:
    active: dev
---
#spring:
#  config:
#    activate:
#      on-profile: h2-local
#  datasource:
#    url: jdbc:h2:mem:testdb;NON_KEYWORDS=USER;DB_CLOSE_ON_EXIT=FALSE;
#    driver-class-name: org.h2.Driver
#    username: sa
#    password:
#  jpa:
#    hibernate:
#      ddl-auto: create
#    properties:
#      hibernate:
#        format_sql: true
#        show_sql: true
#        dialect: org.hibernate.dialect.H2Dialect
#    #        default_read_only: false
#    open-in-view: false
#  h2:
#    console:
#      enabled: true
#      path: /h2-console
#
#  logging:
#    level:
#      org.hibernate.orm.jdbc.bind: trace

---
spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: "jdbc:mysql://localhost:23308/hhplus"
    username: "root"
    password: "root"
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false

  data:
    redis:
      host: localhost
      port: 6379

  kafka:
    bootstrap-servers:
      - localhost:9092
      - localhost:9093
      - localhost:9094
    consumer:
      group-id: concert-ticketing-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

  logging:
    level:
      org.springframework.cache: trace # Redis ??? ?? ??? ????? ??

topic:
  payment: PAYMENT
---
#spring:
#  application:
#    name: hhplus
#  profiles:
#    active: local
spring:
  config:
    activate:
      on-profile: test
  datasource:
    name: HangHaePlusDataSource
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 3
      connection-timeout: 10000
      max-lifetime: 60000
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    open-in-view: false
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate.timezone.default_storage: NORMALIZE_UTC
      hibernate.jdbc.time_zone: UTC

---
#spring.config.activate.on-profile: local, test
spring:
  config:
    activate:
      on-profile: local, test
  datasource:
    url: jdbc:mysql://localhost:3305/hhplus?characterEncoding=UTF-8&serverTimezone=UTC
    username: application
    password: application

  logging:
    level:
      org.springframework.cache: trace # Redis ??? ?? ??? ????? ??